/**:
  ros__parameters:
    waypoints_names: ["entrance", "party", "guest_confirmation", "follow_ready"]
    waypoints: # [x, y, yaw] only 3 numbers!!
      entrance: [2.598, -4.170, -3.065]
      party: [7.964, -4.573, -1.081]
      guest_confirmation: [8.930, -4.273, 2.78]
      follow_ready: [8.64, -4.121, 1.577]

hri_challenge_master:
  ros__parameters:
    flows: [flow_1, flow_2]
    flow_1: [greeting_guest_cognitive_module, describe_person_cognitive_module, find_seat_cognitive_module]
    flow_2: [greeting_guest_cognitive_module, grab_bag_cognitive_module, introduce_guest_cognitive_module, find_seat_cognitive_module, transport_bag_cognitive_module]
    on_startup: [greeting_guest_cognitive_module]  # Node auto-activates HAS TO BE INSIDE FLOW 1


greeting_guest_cognitive_module:
  ros__parameters:
    core: execute_bt
    efferent: transition_output
    plugin_list:
    - activation_control_bt_node
    - init_receptionist_bt_node
    - look_at_bt_node
    - speak_bt_node
    - is_detected_bt_node
    - pan_bt_node
    - filter_entity_bt_node
    - extract_entity_color_bt_node
    - listen_bt_node
    - query_bt_node
    - dialogConfirmation_bt_node
    - store_detection_bt_node
    - move_to_bt_node
    - check_policy_bt_node
    - store_guest_info_bt_node
    - sleep_bt_node
    - store_identity_vector_bt_node
    - enable_detect_by_identity_bt_node
    - get_attended_guest_bt_node
    - remove_string_prefix_bt_node
    - set_head_joint_position_bt_node
    - remove_guest_attended_bt_node
    - remove_guest_facts_bt_node
    - explain_bt_node
    bt_name: 'greeting_guest.xml'
    # New completion topic for flow management
    transition_output:
      topics: ['greeting_guest_cognitive_module/completion', 'bt_status']
      types: ['std_msgs/msg/Bool', 'diagnostic_msgs/msg/KeyValue']


find_seat_cognitive_module:
  ros__parameters:
    core: execute_bt
    efferent: transition_output
    plugin_list:
    - init_receptionist_bt_node
    - activation_control_bt_node
    - move_to_bt_node
    - is_sittable_bt_node
    - point_at_bt_node
    - play_motion_predefined_bt_node
    - speak_bt_node
    - is_detected_bt_node
    - pan_bt_node
    - look_at_bt_node
    - sleep_bt_node
    - remove_string_prefix_bt_node
    - get_attended_guest_bt_node
    - remove_guest_attended_bt_node
    - check_policy_bt_node
    - remove_guest_attended_bt_node
    - set_torso_height_bt_node    
    - explain_bt_node
    bt_name: 'find_seat.xml'
    transition_output:
      topics: ['find_seat_cognitive_module/completion', 'bt_status']
      types: ['std_msgs/msg/Bool', 'diagnostic_msgs/msg/KeyValue']


describe_person_cognitive_module:
  ros__parameters:
    core: execute_bt
    efferent: transition_output
    plugin_list:
    - activation_control_bt_node
    - init_receptionist_bt_node
    - is_detected_bt_node
    - pan_bt_node
    - look_at_bt_node
    - speak_bt_node
    - move_along_axis_bt_node
    - get_guest_info_bt_node
    - move_to_bt_node
    - get_attended_guest_bt_node
    - sleep_bt_node
    - store_identity_vector_bt_node
    - enable_detect_by_identity_bt_node
    - explain_bt_node
    - set_torso_height_bt_node
    - set_head_joint_position_bt_node
    - switch_yolo_model_bt_node
    bt_name: 'describe_person.xml'
    transition_output:
      topics: ['describe_person_cognitive_module/completion', 'bt_status']
      types: ['std_msgs/msg/Bool', 'diagnostic_msgs/msg/KeyValue']


grab_bag_cognitive_module:
  ros__parameters:
    core: execute_bt
    efferent: transition_output
    plugin_list:
    - move_to_predefined_bt_node
    - filter_entity_bt_node
    - look_at_bt_node
    - speak_bt_node
    - is_detected_bt_node
    - sleep_bt_node
    - extract_handover_alignment_bt_node
    - set_torso_height_bt_node
    - move_along_axis_bt_node
    - move_joint_bt_node
    - switch_yolo_model_bt_node
    - init_receptionist_bt_node
    - play_motion_predefined_bt_node
    - get_model_path_bt_node
    - enable_detect_by_identity_bt_node
    - activation_control_bt_node
    - explain_bt_node
    bt_name: 'grab_bag.xml'
    transition_output:
      topics: ['grab_bag_cognitive_module/completion', 'bt_status']
      types: ['std_msgs/msg/Bool', 'diagnostic_msgs/msg/KeyValue']


transport_bag_cognitive_module:
  ros__parameters:
    core: execute_bt
    efferent: transition_output
    plugin_list:
    # - init_hri_challenge_bt_node
    - is_detected_bt_node
    - filter_entity_bt_node
    - look_at_bt_node
    - is_entity_moving_bt_node
    - follow_entity_bt_node
    - goal_publisher_bt_node
    - dialogConfirmation_bt_node
    - speak_bt_node
    - move_to_bt_node
    - sleep_bt_node
    - remove_string_prefix_bt_node
    - add_string_suffix_bt_node
    - set_persistent_id_bt_node
    - init_receptionist_bt_node
    - activation_control_bt_node
    - enable_detect_by_identity_bt_node
    - explain_bt_node
    - play_motion_predefined_bt_node

    bt_name: 'transport_bag.xml'
    transition_output:
      topics: ['transport_bag_cognitive_module/completion', 'bt_status']
      types: ['std_msgs/msg/Bool', 'diagnostic_msgs/msg/KeyValue']


introduce_guest_cognitive_module:
  ros__parameters:
    core: execute_bt
    efferent: transition_output
    plugin_list:
    - activation_control_bt_node
    - init_receptionist_bt_node
    - look_at_bt_node
    - speak_bt_node
    - is_detected_bt_node
    - pan_bt_node
    - filter_entity_bt_node
    - extract_entity_color_bt_node
    - listen_bt_node
    - query_bt_node
    - dialogConfirmation_bt_node
    - store_detection_bt_node
    - move_to_bt_node
    - check_policy_bt_node
    - store_guest_info_bt_node
    - sleep_bt_node
    - store_identity_vector_bt_node
    - enable_detect_by_identity_bt_node
    - get_attended_guest_bt_node
    - get_guest_info_bt_node
    - move_along_axis_bt_node
    - explain_bt_node
    - set_torso_height_bt_node


    bt_name: 'introduce_guest.xml'
    transition_output:
      topics: ['introduce_guest_cognitive_module/completion', 'bt_status']
      types: ['std_msgs/msg/Bool', 'diagnostic_msgs/msg/KeyValue']